import cv2
import numpy
import math
from enum import Enum

class GripPipeline:
    """
    An OpenCV pipeline generated by GRIP.
    """
    
    def __init__(self):
        """initializes all values to presets or None if need to be set
        """

        self.__hsv_threshold_0_hue = [0.0, 180.0]
        self.__hsv_threshold_0_saturation = [0.0, 46.608084358523705]
        self.__hsv_threshold_0_value = [95.82926878835913, 133.80962525075003]

        self.hsv_threshold_0_output = None

        self.__normalize_input = self.hsv_threshold_0_output
        self.__normalize_type = cv2.NORM_MINMAX
        self.__normalize_alpha = 0.0
        self.__normalize_beta = 255.0

        self.normalize_output = None

        self.__blur_input = self.normalize_output
        self.__blur_type = BlurType.Box_Blur
        self.__blur_radius = 4.716981132075472

        self.blur_output = None

        self.__find_lines_0_input = self.blur_output

        self.find_lines_0_output = None

        self.__filter_lines_0_lines = self.find_lines_0_output
        self.__filter_lines_0_min_length = 300.0
        self.__filter_lines_0_angle = [157.83582089552237, 203.205574912892]

        self.filter_lines_0_output = None


        self.__hsv_threshold_1_hue = [0.0, 180.0]
        self.__hsv_threshold_1_saturation = [0.0, 55.57117750439366]
        self.__hsv_threshold_1_value = [213.70056497175142, 255.0]

        self.hsv_threshold_1_output = None

        self.__find_lines_1_input = self.hsv_threshold_1_output

        self.find_lines_1_output = None

        self.__filter_lines_1_lines = self.find_lines_1_output
        self.__filter_lines_1_min_length = 100.0
        self.__filter_lines_1_angle = [0.0, 242.95254833040423]

        self.filter_lines_1_output = None


    def process(self, source0, source1):
        """
        Runs the pipeline and sets all outputs to new values.
        """
        # Step HSV_Threshold0:
        self.__hsv_threshold_0_input = source0
        (self.hsv_threshold_0_output) = self.__hsv_threshold(self.__hsv_threshold_0_input, self.__hsv_threshold_0_hue, self.__hsv_threshold_0_saturation, self.__hsv_threshold_0_value)

        # Step Normalize0:
        self.__normalize_input = self.hsv_threshold_0_output
        (self.normalize_output) = self.__normalize(self.__normalize_input, self.__normalize_type, self.__normalize_alpha, self.__normalize_beta)

        # Step Blur0:
        self.__blur_input = self.normalize_output
        (self.blur_output) = self.__blur(self.__blur_input, self.__blur_type, self.__blur_radius)

        # Step Find_Lines0:
        self.__find_lines_0_input = self.blur_output
        (self.find_lines_0_output) = self.__find_lines(self.__find_lines_0_input)

        # Step Filter_Lines0:
        self.__filter_lines_0_lines = self.find_lines_0_output
        (self.filter_lines_0_output) = self.__filter_lines(self.__filter_lines_0_lines, self.__filter_lines_0_min_length, self.__filter_lines_0_angle)

        # Step HSV_Threshold1:
        self.__hsv_threshold_1_input = source1
        (self.hsv_threshold_1_output) = self.__hsv_threshold(self.__hsv_threshold_1_input, self.__hsv_threshold_1_hue, self.__hsv_threshold_1_saturation, self.__hsv_threshold_1_value)

        # Step Find_Lines1:
        self.__find_lines_1_input = self.hsv_threshold_1_output
        (self.find_lines_1_output) = self.__find_lines(self.__find_lines_1_input)

        # Step Filter_Lines1:
        self.__filter_lines_1_lines = self.find_lines_1_output
        (self.filter_lines_1_output) = self.__filter_lines(self.__filter_lines_1_lines, self.__filter_lines_1_min_length, self.__filter_lines_1_angle)


    @staticmethod
    def __normalize(input, type, a, b):
        """Normalizes or remaps the values of pixels in an image.
        Args:
            input: A numpy.ndarray.
            type: Opencv enum.
            a: The minimum value.
            b: The maximum value.
        Returns:
            A numpy.ndarray of the same type as the input.
        """
        return cv2.normalize(input, None, a, b, type)

    @staticmethod
    def __blur(src, type, radius):
        """Softens an image using one of several filters.
        Args:
            src: The source mat (numpy.ndarray).
            type: The blurType to perform represented as an int.
            radius: The radius for the blur as a float.
        Returns:
            A numpy.ndarray that has been blurred.
        """
        if(type is BlurType.Box_Blur):
            ksize = int(2 * round(radius) + 1)
            return cv2.blur(src, (ksize, ksize))
        elif(type is BlurType.Gaussian_Blur):
            ksize = int(6 * round(radius) + 1)
            return cv2.GaussianBlur(src, (ksize, ksize), round(radius))
        elif(type is BlurType.Median_Filter):
            ksize = int(2 * round(radius) + 1)
            return cv2.medianBlur(src, ksize)
        else:
            return cv2.bilateralFilter(src, -1, round(radius), round(radius))

    @staticmethod
    def __hsv_threshold(input, hue, sat, val):
        """Segment an image based on hue, saturation, and value ranges.
        Args:
            input: A BGR numpy.ndarray.
            hue: A list of two numbers the are the min and max hue.
            sat: A list of two numbers the are the min and max saturation.
            lum: A list of two numbers the are the min and max value.
        Returns:
            A black and white numpy.ndarray.
        """
        out = cv2.cvtColor(input, cv2.COLOR_BGR2HSV)
        return cv2.inRange(out, (hue[0], sat[0], val[0]),  (hue[1], sat[1], val[1]))

    class Line:

        def __init__(self, x1, y1, x2, y2):
            self.x1 = x1
            self.y1 = y1
            self.x2 = x2
            self.y2 = y2

        def length(self):
            return numpy.sqrt(pow(self.x2 - self.x1, 2) + pow(self.y2 - self.y1, 2))

        def angle(self):
            return math.degrees(math.atan2(self.y2 - self.y1, self.x2 - self.x1))
    @staticmethod
    def __find_lines(input):
        """Finds all line segments in an image.
        Args:
            input: A numpy.ndarray.
        Returns:
            A filtered list of Lines.
        """
        detector = cv2.createLineSegmentDetector()
        if (len(input.shape) == 2 or input.shape[2] == 1):
            lines = detector.detect(input)
        else:
            tmp = cv2.cvtColor(input, cv2.COLOR_BGR2GRAY)
            lines = detector.detect(tmp)
        output = []
        if len(lines) != 0 and lines[0] != None:
            for i in range(1, len(lines[0])):
                tmp = GripPipeline.Line(lines[0][i, 0][0], lines[0][i, 0][1],
                                lines[0][i, 0][2], lines[0][i, 0][3])
                output.append(tmp)
        return output

    @staticmethod
    def __filter_lines(inputs, min_length, angle):
        """Filters out lines that do not meet certain criteria.
        Args:
            inputs: A list of Lines.
            min_Lenght: The minimum lenght that will be kept.
            angle: The minimum and maximum angles in degrees as a list of two numbers.
        Returns:
            A filtered list of Lines.
        """
        outputs = []
        for line in inputs:
            if (line.length() > min_length):
                if ((line.angle() >= angle[0] and line.angle() <= angle[1]) or
                        (line.angle() + 180.0 >= angle[0] and line.angle() + 180.0 <= angle[1])):
                    outputs.append(line)
        return outputs


BlurType = Enum('BlurType', 'Box_Blur Gaussian_Blur Median_Filter Bilateral_Filter')

